version: '3.9'

services:
  webscrp:
    image: vot/webscrp
    restart: always
    expose: 
      - "80"
    deploy:
      replicas: 5

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webscrp
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge
    name: webscrp